server:
  port: 8082
spring:
  liquibase:
    change-log: classpath:liquibase/changelog.master.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none